### ISSUE TITLE
Old database being overwritten after each restart of the service

### ISSUE THREAD

**Issue by ztybigcat** [SlangLab-NU/VoiceCollector#34]
Version: 1.1.0
The voice collector metadata database is being overwritten each time the service is restarted. 
To recreate the bug:
1. start voice collector and submit a few recordings, recordings can be seen by manually loading the database with sqlite3 command:
```
[ec2-user@ip-sqlite]$ sqlite3 database_bk.db
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> SELECT * FROM audio;
1|36.85311378639757|test36.85311378639757.webm|2023-11-09 02:05:36|1
2|60.70481385834216|test60.70481385834216.webm|2023-11-09 02:39:39|1
3|85.5732171060326|test85.5732171060326.webm|2023-11-09 02:39:56|2
```
2. After restarting the services, a manual inspection of the database.db file showing none of the old recordings:
```
[ec2-user@ip- sqlite]$ sqlite3 database.db 
SQLite version 3.7.17 2013-05-20 00:56:22
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> SELECT * FROM audio;
```

**Comment by jindaxz** [comment]
Hi @ztybigcat I am currently working on this ticket. Could you indicate how to submit audio file to sqlite3? Idk whats public IP address of EC2 instance, and how to access front end of it. Feel free to DM me if is confidential and not convient to share publicly.

**Comment by ztybigcat** [comment]
Hi @jindaczmatrix ,
Our site is at [https://voicecollector.happyprime.io](https://voicecollector.happyprime.io). I already added your public key to it so you can try ssh into it. Once you submit a few recordings and restart the service you should be able to recreate the bug.
Please let me know on Discord if you have trouble accessing it.
